name: "back up test"

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "The base branch to merge into"
        required: true
      head_branch:
        description: "The branch to merge from"
        required: true

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Checkout head branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.head_branch }}
          path: head-branch

      - name: Attempt to merge
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout ${{ github.event.inputs.base_branch }}
          git merge --no-commit --no-ff head-branch
